Repository involvestecnologia/statuspage, pull requests merged in 2019-02, with the labels that each got.

#13 add new parameter to component list
  Makefile
  component/controller.go
  component/controller_test.go
  component/interface.go
  component/routes.go
  component/service.go
  component/service_test.go
  docker-compose.yml
  models/component.go
Labels: enhancement

#14 lint and some minor fixes
  client/controller.go
  client/controller_test.go
  client/mongodb_repository.go
  client/mongodb_repository_test.go
  client/routes.go
  client/service.go
  client/service_test.go
  component/controller.go
  component/controller_test.go
  component/mongodb_repository.go
  component/mongodb_repository_test.go
  component/routes.go
  component/service.go
  db/mongodb.go
  errors/errors.go
  incident/controller.go
  incident/controller_test.go
  incident/mongodb_repository.go
  incident/mongodb_repository_test.go
  incident/routes.go
  incident/service.go
  main.go
  middleware/cors.go
  models/component.go
  models/incident.go
  models/prometheus.go
  prometheus/controller.go
  prometheus/controller_test.go
  prometheus/interface.go
  prometheus/routes.go
  prometheus/routes_test.go
  prometheus/service.go
  webhook/routes.go
Labels: enhancement

#16 minor change in README and test CI webhook
  README.md
Labels: version:patch

#18 make sure incidents get timed
  prometheus/service.go
Labels: bug, version:patch

#19 check if it's zero before overwrite Incident time
  prometheus/service.go
Labels: enhancement, version:patch

#20 Add new query param and functions
  errors/errors.go
  incident/controller.go
  incident/interface.go
  incident/mongodb_repository.go
  incident/service.go
  models/incident.go
  models/prometheus.go
  prometheus/service.go
Labels: enhancement

#24 increase tests coverage
  Makefile
  errors/errors.go
  incident/service.go
  incident/service_test.go
  mock/prometheus.go
  models/incident.go
  models/prometheus.go
  prometheus/service_test.go
Labels: tests
